auto_rules = [
    {"id": 1,  "label": "Ondertekening", 
                "words": ["^", "Groet", "Groetjes", "Naam_medewerker"] }, 
    {"id": 2,  "label": "Persoonlijke begroeting", 
                "words": ["Beste", "Naam_klant"] }, 
    {"id": 3,  "label": "Taal", 
                "words": [] }, 
    {"id": 4,  "label": "Afkortingen/verkortingen", 
                "words": ["LOL", "lol", "da's", "aub", 
                    ":)", ";)", ";-)", ":-)", ":(", ";(", ";-(", ":-(", "\ufffd"] }, 
    {"id": 5,  "label": "Imitatie verbale communicatie cues", 
                "words": ["??", "heeel", "heeeel", "MOOI", "oh", "haha", "wow", "zeg", "ai", 
                    "oeps", "oei", "ach", "euh", "ohnee!", "!!"] }, 
    {"id": 6,  "label": "Stimuleren dialoog", 
                "words": ["?", "DM", "ordernummer", "voortzetten", "bericht", "mailadres", 
                    "e-mailadres", "privébericht", "privé bericht", "artikelnummer",
                    "vraag", "vragen", "bestelnummer", "3S-code"] }, 
    {"id": 7,  "label": "Bedanken", 
                "words": ["dankjewel", "bedankt", "dank"] }, 
    {"id": 8,  "label": "Tonen sympathie/empathie", 
                "words": ["niet best", "niet zo fijn", "niet fijn", "snap", "snappen", "vervelend", 
                    "jammer", "begrijpelijk", "gelukkig","wat zonde", "voorstellen", "balen", "baalt", 
                    "wat rot", "wat naar", "helaas", 
                    ":)", ";)", ";-)", ":-)", ":(", ";(", ";-(", ":-(", "\ufffd"] }, 
    {"id": 9,  "label": "Verontschuldigen", 
                "words": ["excuses", "sorry", "spijt", "excuus"] }, 
    {"id": 10, "label": "Humor", 
                "words": ["lachen", "haha"] }, 
    {"id": 11, "label": "Uitleg", 
                "words": ["omdat", "meer over", "waardoor", "door", "heeft het te maken met", "het heeft te maken met", 
                    "vandaar", "dit doen we om", "waarschijnlijk is dat waarom", "dit betekent", "daarom", 
                    "daardoor", "namelijk", "we", "voorraad", "leverbaar", "verwachten"] }, 
    {"id": 12, "label": "Reversed blame", 
                "words": ["bezorgers", "bezorger", "bezorgdienst", "hun", "partners", "verkooppartners", "verkoper"] }, 
    {"id": 13, "label": "Hoop dat de klant terugkeert", 
                "words": ["hopelijk", "tot ziens", "volgende bestelling"] }, 
    {"id": 14, "label": "Herhaling pos. argumenten", 
                "words": ["inderdaad", "fijn", "tevreden", "leuk"] }, 
    {"id": 15, "label": "Downtonen", 
                "words": ["niet zo handig", "niet handig", "teleurgesteld", "onhandig", "niet zo prettig", 
                    "niet prettig", "balen", "baalt", "fout gegaan", "kleine blunder"] }, 
    {"id": 16, "label": "Actie nemen", 
                "words": ["achteraan", "afdeling", "doorgeven", "zetten het door", "doorzetten naar", "feedback",
                    "melding", "melden", "intern", "aankaarten", "onderzoek", "er is direct", "we hebben direct", 
                    "ervoor zorgen dat"] },
    {"id": 17, "label": "Polariteit", 
                "custom": "polarity" }, 
    {"id": 18, "label": "Subjectivity", 
                "custom": "subjectivity" }, 
    ]
